#!/bin/bash
#Author: Joe Benjamin







#
# dotnet-build-package-sln
# use this function to build and package dotnet solutions
# first package directory with sln
# must be in the directory of the sln 
# script will loop through subdirectories where aws-lambda-tools-default.json files exists
# will package those directories
# wip
#
dotnet-build-package-sln(){
  local MESSAGECOLOR='\033[0;32m'
  local RESET='\033[0m'
  if ls *.sln 2> /dev/null; then
    echo -e "${MESSAGECOLOR} building directory $dir: dotnet build ${RESET}"
    dotnet build
    currdir=$(pwd)
    find . -name "aws-lambda-tools-defaults.json" |
    for file in $(cat); do
      local dir=$(dirname $file)
      echo -e "${MESSAGECOLOR} changing directory: cd $dir ${RESET}"
      cd $dir
      echo -e "${MESSAGECOLOR} packaging directory $dir: dotnet lambda package ${RESET}"
      dotnet lambda package
    done
    echo -e "${MESSAGECOLOR} changing directory: cd $currdir ${RESET}"
    cd $currdir
  else
    echo "go to root of sln folder and run again"
  fi
}
